name: Header Comments CI
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Add comments
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Add comments to src/
        uses: myvikasit/header-comments@main
        with:
          directory: src
      - name: Publish comments
        uses: stefanzweifel/git-auto-commit-action@v4.10.0
        with:
          commit_message: ":bulb: Add header comments [skip ci]"
          commit_user_name: Vikasit Bot
          commit_user_email: bot@vikasit.com
          commit_author: Vikasit Bot <bot@vikasit.com>
